name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Optimize images
        run: |
          npx imagemin 'public/**/*.{jpg,jpeg,png,svg,webp}' --out-dir=public
          echo "✅ 圖片已壓縮完成"

      - name: Clean previous build
        run: rm -rf dist

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Clear GitHub Pages cache
        run: |
          echo "嘗試清除快取 (GitHub Pages + 瀏覽器)"
          echo "⚠️ 如果頁面看起來沒更新，請手動 Ctrl+F5 強制刷新"
